name: Python CI

on:
  push:
    branches: [main, anastasia_dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 cargame/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run tests
        run: |
          pytest cargame/tests --maxfail=3 --disable-warnings --html=report.html
